FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn -B clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /app/target/eligibility-service-0.0.1.jar app.jar

EXPOSE 8093

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
