server:
  port: 8093

spring:
  application:
    name: eligibility-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: eligibility-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.debish.health.eligibility.application.event
        spring.json.value.default.type: com.debish.health.eligibility.application.event.ClaimValidatedEvent
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  kafka:
    topics:
      claim-validated: claim-validated
      member-eligible: member-eligible
      member-ineligible: member-ineligible

logging:
  file:
    name: ${LOG_FILE_PATH:../../observability/logs/eligibility-service.log}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
