apiVersion: apps/v1
kind: Deployment
metadata:
  name: claim-validation-service
  namespace: healthcare-claims
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claim-validation-service
  template:
    metadata:
      labels:
        app: claim-validation-service
    spec:
      containers:
        - name: claim-validation-service
          image: healthcare/claim-validation-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8092
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: claims-platform-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: claims-platform-config
                  key: CLAIM_VALIDATION_DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: claims-platform-config
                  key: CLAIM_VALIDATION_DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: claims-platform-config
                  key: CLAIM_VALIDATION_DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: claims-platform-secret
                  key: CLAIM_VALIDATION_DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: claims-platform-secret
                  key: CLAIM_VALIDATION_DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: claim-validation-service
  namespace: healthcare-claims
spec:
  selector:
    app: claim-validation-service
  ports:
    - port: 8092
      targetPort: 8092
