apiVersion: v1
kind: Secret
metadata:
  name: claims-platform-secret
  namespace: healthcare-claims
type: Opaque
stringData:
  CLAIMS_DB_USERNAME: claims
  CLAIMS_DB_PASSWORD: claimspw
  CLAIM_VALIDATION_DB_USERNAME: claimvalidation
  CLAIM_VALIDATION_DB_PASSWORD: claimvalidationpw
  PAYMENT_DB_USERNAME: payment
  PAYMENT_DB_PASSWORD: paymentpw
  NOTIFICATION_DB_USERNAME: notification
  NOTIFICATION_DB_PASSWORD: notificationpw
  AUDIT_DB_USERNAME: audit
  AUDIT_DB_PASSWORD: auditpw
