[monitor:///var/log/healthcare/claim-intake-service.log]
disabled = false
index = main
sourcetype = healthcare:service
source = claim-intake-service
host = healthcare-platform-local

[monitor:///var/log/healthcare/claim-validation-service.log]
disabled = false
index = main
sourcetype = healthcare:service
source = claim-validation-service
host = healthcare-platform-local

[monitor:///var/log/healthcare/eligibility-service.log]
disabled = false
index = main
sourcetype = healthcare:service
source = eligibility-service
host = healthcare-platform-local

[monitor:///var/log/healthcare/fraud-check-service.log]
disabled = false
index = main
sourcetype = healthcare:service
source = fraud-check-service
host = healthcare-platform-local

[monitor:///var/log/healthcare/adjudication-service.log]
disabled = false
index = main
sourcetype = healthcare:service
source = adjudication-service
host = healthcare-platform-local

[monitor:///var/log/healthcare/payment-service.log]
disabled = false
index = main
sourcetype = healthcare:service
source = payment-service
host = healthcare-platform-local

[monitor:///var/log/healthcare/notification-service.log]
disabled = false
index = main
sourcetype = healthcare:service
source = notification-service
host = healthcare-platform-local

[monitor:///var/log/healthcare/audit-service.log]
disabled = false
index = main
sourcetype = healthcare:service
source = audit-service
host = healthcare-platform-local

[monitor:///var/log/healthcare/patient-rest-service.log]
disabled = false
index = main
sourcetype = healthcare:service
source = patient-rest-service
host = healthcare-platform-local

[monitor:///var/log/healthcare/clinic-soap-service.log]
disabled = false
index = main
sourcetype = healthcare:service
source = clinic-soap-service
host = healthcare-platform-local
